POST http://localhost:9993
###

POST http://localhost:9993/feedback
Content-Type: application/json

{"feedback_topic": "Парковка",
  "feedback_by": "Anonim",
  "feedback_to": "Vasya Petrov",
  "feedback_text": "Парковался в неположенном месте",
  "score": 0
}
###





GET http://localhost:9993/feedback/all

###
POST http://localhost:9993/feedback/edit/69a39dea-f3b3-4c0c-a0f2-7e33d4fad018

{"feedback_topic": "Уборка",
  "feedback_by": "Anonim",
  "feedback_to": "Alisher Vazilov",
  "feedback_text": "увидел, что кружки грязные и помыл все!",
  "score": 10
}
###
DELETE http://localhost:9993/feedback/69a39dea-f3b3-4c0c-a0f2-7e33d4fad018



###
